tagFormat: ${version}
debug: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/git"
  - "@semantic-release/github"
  - ["@semantic-release/exec", { "verifyReleaseCmd": "echo \"${nextRelease.version}\" > next.version" }]
branches:
  - name: 'main'
