tagFormat: ${version}
debug: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/git"
  - "@semantic-release/github"
  - ["@semantic-release/exec", { "publishCmd": "echo \"VERSION=${nextRelease.version}\"" }]
branches:
  - name: 'main'
