# This workflow takes care about release versions in the code
name: SemVer Update

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  # build library
  next-release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Semantic release
        run: |
          sudo npm install -g \
            semantic-release@18.0.0 \
            @semantic-release/git@10.0.0 \
            @semantic-release/release-notes-generator@10.0.2 \
            @semantic-release/github@8.0.0 \
            @semantic-release/exec@6.0.3

      - name: Determine Version
        run: |
          cat .release
          semantic-release --no-ci --dry-run | tee semver-out.txt
