# This workflow takes care about release versions in the code
name: SemVer Update

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  # build library
  next-release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Semantic release
        run: |
          sudo npm install -g \
            semantic-release@18.0.0 \
            @semantic-release/git@10.0.0 \
            @semantic-release/release-notes-generator@10.0.2 \
            @semantic-release/github@8.0.0 \
            @semantic-release/exec@6.0.3

      - name: Disable Semantic Release GitHub Plugin
        # Disable GitHub plugin as it requires more access than available.
        run: |
          cat ".releaserc.yaml" | grep -v "semantic-release/github" > ".releaserc-new.yaml"
          mv -f ".releaserc-new.yaml" ".releaserc.yaml"

      - name: Determine Version
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          semantic-release --ci false --dry-run -b "${BRANCH_NAME}" --exec 

      - name: Do something with next version
        run: |
          cat next.version
          cat current-version.txt
